class FLAGS:
	image_dir='./train_61326'
	output_graph='logs/trained_graph.pb'
	output_labels='logs/trained_labels.txt'
	summaries_dir='logs/training_summaries/basic'
	how_many_training_steps=2000
	learning_rate=0.01
	testing_percentage=10
	validation_percentage=10
	eval_step_interval=100
	train_batch_size=100
	test_batch_size=-1
	validation_batch_size=100
	model_dir='inception'
	bottleneck_dir='logs/bottlenecks'
	final_tensor_name='final_result'
	flip_left_right=False
	random_crop=0
	random_scale=0
	random_brightness=0
	DATA_URL = 'http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz'
	BOTTLENECK_TENSOR_NAME = 'pool_3/_reshape:0'
	BOTTLENECK_TENSOR_SIZE = 2048
	MODEL_INPUT_WIDTH = 299
	MODEL_INPUT_HEIGHT = 299
	MODEL_INPUT_DEPTH = 3
	JPEG_DATA_TENSOR_NAME = 'DecodeJpeg/contents:0'
	RESIZED_INPUT_TENSOR_NAME = 'ResizeBilinear:0'
	MAX_NUM_IMAGES_PER_CLASS = 20  # ~134M
